name: club_app_new
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # CORE PLUGINS
  provider: ^6.1.2
  cupertino_icons: ^1.0.8

  # FIREBASE PLUGINS (Updated to modern, compatible versions)
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # OTHER PLUGINS
  image_picker: ^1.1.2
  cloudinary_public: ^0.23.1
  google_sign_in: ^6.2.1 # This was the main source of errors
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # This is a development tool, so it belongs in dev_dependencies
  change_app_package_name: ^1.2.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/