// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7wseFqrTO6F1yajfhbwTsYdl6yxJ6bQ',
    appId: '1:476263611129:android:22ad43148b8ad2ad794028',
    messagingSenderId: '476263611129',
    projectId: 'clubappfinal',
    storageBucket: 'clubappfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6gkMKiYn2tnmJ55IgFjYUF3xfFi-Ivyw',
    appId: '1:476263611129:ios:cb36b9377779e326794028',
    messagingSenderId: '476263611129',
    projectId: 'clubappfinal',
    storageBucket: 'clubappfinal.firebasestorage.app',
    iosBundleId: 'com.syntex.club',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqPwxMwknGJk_4opb8P20akKEoChs2qFk',
    appId: '1:476263611129:web:a867b37617628a54794028',
    messagingSenderId: '476263611129',
    projectId: 'clubappfinal',
    authDomain: 'clubappfinal.firebaseapp.com',
    storageBucket: 'clubappfinal.firebasestorage.app',
    measurementId: 'G-35QFVZ6H8V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6gkMKiYn2tnmJ55IgFjYUF3xfFi-Ivyw',
    appId: '1:476263611129:ios:d53ffa6bf963cd60794028',
    messagingSenderId: '476263611129',
    projectId: 'clubappfinal',
    storageBucket: 'clubappfinal.firebasestorage.app',
    iosBundleId: 'com.example.clubAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqPwxMwknGJk_4opb8P20akKEoChs2qFk',
    appId: '1:476263611129:web:c6e8c3f0edc639a3794028',
    messagingSenderId: '476263611129',
    projectId: 'clubappfinal',
    authDomain: 'clubappfinal.firebaseapp.com',
    storageBucket: 'clubappfinal.firebasestorage.app',
    measurementId: 'G-L0TCBV0YR1',
  );

}